// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricingTool.Data;

#nullable disable

namespace PricingTool.Data.Migrations
{
    [DbContext(typeof(PricingToolDbContext))]
    [Migration("20260619115102_AddCrossDockAlgorithm")]
    partial class AddCrossDockAlgorithm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PricingTool")
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PricingTool.Data.Entities.AlgorithmVoteRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AlgorithmCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("BandWeight")
                        .HasColumnType("int");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("EffectiveWeight")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<long>("ProposedPriceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<decimal>("SuggestedPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmCode");

                    b.HasIndex("ProposedPriceId");

                    b.ToTable("AlgorithmVotes", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("LayerId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LayerId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AuditLog", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.BandAlgorithmSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgorithmCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("PriceBandId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PriceBandId", "AlgorithmCode")
                        .IsUnique();

                    b.ToTable("BandAlgorithmSettings", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.DailySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AnchorPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentDiscountPct")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Disc14")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Disc30")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Disc60")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Disc7")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Disc90")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("GrossMargin")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTime?>("LaunchDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LayerId")
                        .HasColumnType("int");

                    b.Property<int>("LocalWarehouseStock")
                        .HasColumnType("int");

                    b.Property<decimal>("Net14")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Net30")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Net60")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Net7")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Net90")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Pptcv")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("PulledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Qty14")
                        .HasColumnType("int");

                    b.Property<int>("Qty30")
                        .HasColumnType("int");

                    b.Property<int>("Qty60")
                        .HasColumnType("int");

                    b.Property<int>("Qty7")
                        .HasColumnType("int");

                    b.Property<int>("Qty90")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<int>("SupplierWarehouseStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sku");

                    b.HasIndex("LayerId", "SnapshotDate", "Sku")
                        .IsUnique();

                    b.ToTable("DailySnapshots", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.Layer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CadenceHours")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("ExcludeUnpublished")
                        .HasColumnType("bit");

                    b.Property<bool>("FilterVendors")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastElasticityFitUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastScheduledRunUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationalDatabase")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RunTimeUtc")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("SrCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("SrPlatformId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("TranslationCountryId")
                        .HasColumnType("int");

                    b.Property<decimal>("VatRatePct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("WarehouseStoreId")
                        .HasColumnType("int");

                    b.Property<int>("WmsWarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Brand", "CountryCode")
                        .IsUnique();

                    b.ToTable("Layers", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.PriceBand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("MarginFloorPct")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("MaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("RoundingConvention")
                        .HasColumnType("int");

                    b.Property<bool>("RoundingEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LayerId");

                    b.ToTable("PriceBands", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.PriceChangeOutcome", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AppliedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("Intent")
                        .HasColumnType("int");

                    b.Property<int>("LayerId")
                        .HasColumnType("int");

                    b.Property<long?>("MeasuredOnRunId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MeasuredUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NewPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PostGrossProfitPerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PostMarginPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PostUnitsPerDay")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal?>("PreGrossProfitPerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PreMarginPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PreUnitsPerDay")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<int?>("PriceBandId")
                        .HasColumnType("int");

                    b.Property<long?>("ProposedPriceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("SourceRunId")
                        .HasColumnType("bigint");

                    b.Property<int>("Verdict")
                        .HasColumnType("int");

                    b.Property<int>("WindowDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppliedUtc");

                    b.HasIndex("LayerId");

                    b.HasIndex("ProposedPriceId")
                        .IsUnique()
                        .HasFilter("[ProposedPriceId] IS NOT NULL");

                    b.HasIndex("Verdict");

                    b.ToTable("PriceChangeOutcomes", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.PricingRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOnDemand")
                        .HasColumnType("bit");

                    b.Property<int>("LayerId")
                        .HasColumnType("int");

                    b.Property<int>("ProposalCount")
                        .HasColumnType("int");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int");

                    b.Property<int>("SkuCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("StartedUtc");

                    b.HasIndex("LayerId", "Status");

                    b.ToTable("PricingRuns", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.ProposedPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AbsChangePct")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)")
                        .HasComputedColumnSql("ABS([ChangePct])");

                    b.Property<decimal>("AnchorPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangePct")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GuardrailFlags")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("HasChange")
                        .HasColumnType("bit");

                    b.Property<int>("LayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Pptcv")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("PriceBandId")
                        .HasColumnType("int");

                    b.Property<long>("PricingRunId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ProposedPriceValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PushedUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RawWeightedPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ReasonCodes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ReviewedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LayerId");

                    b.HasIndex("Sku");

                    b.HasIndex("Status");

                    b.HasIndex("PricingRunId", "Sku")
                        .IsUnique();

                    b.HasIndex("PricingRunId", "Status", "AbsChangePct");

                    b.ToTable("ProposedPrices", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.SkuElasticity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Coefficient")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("DistinctPricePoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("FittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Intercept")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsUsable")
                        .HasColumnType("bit");

                    b.Property<int>("LayerId")
                        .HasColumnType("int");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceCv")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.Property<decimal>("R2")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("StandardError")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("Id");

                    b.HasIndex("LayerId", "IsUsable");

                    b.HasIndex("LayerId", "Sku")
                        .IsUnique();

                    b.ToTable("SkuElasticity", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.SkuOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LayerId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("RoundingDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LayerId", "Sku")
                        .IsUnique();

                    b.ToTable("SkuOverrides", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.ToolSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Key");

                    b.ToTable("ToolSettings", "PricingTool");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.AlgorithmVoteRecord", b =>
                {
                    b.HasOne("PricingTool.Data.Entities.ProposedPrice", "ProposedPrice")
                        .WithMany("Votes")
                        .HasForeignKey("ProposedPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProposedPrice");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("PricingTool.Data.Entities.Layer", null)
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PricingTool.Data.Entities.BandAlgorithmSetting", b =>
                {
                    b.HasOne("PricingTool.Data.Entities.PriceBand", "PriceBand")
                        .WithMany("AlgorithmSettings")
                        .HasForeignKey("PriceBandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceBand");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.DailySnapshot", b =>
                {
                    b.HasOne("PricingTool.Data.Entities.Layer", null)
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PricingTool.Data.Entities.PriceBand", b =>
                {
                    b.HasOne("PricingTool.Data.Entities.Layer", null)
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PricingTool.Data.Entities.PriceChangeOutcome", b =>
                {
                    b.HasOne("PricingTool.Data.Entities.Layer", null)
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PricingTool.Data.Entities.ProposedPrice", "ProposedPrice")
                        .WithMany()
                        .HasForeignKey("ProposedPriceId");

                    b.Navigation("ProposedPrice");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.PricingRun", b =>
                {
                    b.HasOne("PricingTool.Data.Entities.Layer", null)
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PricingTool.Data.Entities.ProposedPrice", b =>
                {
                    b.HasOne("PricingTool.Data.Entities.Layer", null)
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PricingTool.Data.Entities.PricingRun", "PricingRun")
                        .WithMany("Proposals")
                        .HasForeignKey("PricingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingRun");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.SkuElasticity", b =>
                {
                    b.HasOne("PricingTool.Data.Entities.Layer", null)
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PricingTool.Data.Entities.SkuOverride", b =>
                {
                    b.HasOne("PricingTool.Data.Entities.Layer", null)
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PricingTool.Data.Entities.PriceBand", b =>
                {
                    b.Navigation("AlgorithmSettings");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.PricingRun", b =>
                {
                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("PricingTool.Data.Entities.ProposedPrice", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
